version: "3.8"
services:
  shopdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Asdfr678
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - shopdb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shop" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres
  server:
    build: server/
    command: npm start
    volumes:
      - /home/georgiy/web/shop/server:/server
    ports:
      - 5000:5000
    depends_on:
      - shopdb
    networks:
      - postgres
  client:
    build: client/
    command: npm start
    volumes:
      - /home/georgiy/web/shop/client:/client
    ports:
      - 80:3000

volumes:
  shopdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
