version: "3.8"
services:
  shopdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - shopdb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shop" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres
  server:
    build: server/
    command: npm start
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      - shopdb
    networks:
      - postgres
  client:
    build: client/
    command: npm start
    ports:
      - 80:3000
    volumes:
      - ./client:/client
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres

volumes:
  shopdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
