export const ADMIN_ROUTE = '/admin'
export const AUTH_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'